config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index' #> RAIZ ou seja ROOT
  # get '/', to: 'home#index'
  #resources :manufacturers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :manufacturers
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_categories, only: [:index, :show, :new, :create, :edit, :update]
  resources :customers, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
  resources :cars, only: [:index, :show, :new, :create]

  #get 'api/v1/cars', to: 'api#cars'

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index]
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :rentals

  validates :name, :document, :email, uniqueness: true

  validates :name, :email, :document, presence: true

  validate :cpf_must_be_valid
  validates :document, length: {is: 14}
  validates :document, format: {with: /\d{3}\.\d{3}\.\d{3}\-\d{2}/, message: "Digite os pontos e o traço"}
  
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }


  scope :search, ->(query) { where('name LIKE ?', "%#{query}%")
                                    .or(where(document: query)) }

  #def self.search(query)
  #  where('name LIKE ?', "%#{query}%")
  #end

  private
  def cpf_must_be_valid
    return if CPF.valid?(document, strict: true)
      errors.add(:document)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
    
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
      render :new
    end
  end


  def search
    @customers = Customer.search(params[:q])
    #Customer.where(name: params[:q])
    render :index
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :document, :email)
  end
end

app/views/customers/index.html.erb
<h1>Clientes</h1>

<% if @customers.empty? %>
  <h1>Não há clientes cadastrados</h1>
<% end %>

<% @customers.each do |c| %>
  <h3><%= link_to c.name, customer_path(id: c.id)%></h3>
<% end %>

<%= form_with url: search_customers_path, method: :get do |f| %>
  <%= f.label :q, 'Busca' %>
  <%= f.search_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Documento</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr id="car-model-<%= customer.id %>">
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.document %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Registrar novo cliente', new_customer_path %>
<%= link_to 'Voltar', root_path %>

app/views/customers/new.html.erb
<h1>Registrar cliente</h1>

<% @customer.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_for @customer do |c| %>
  <%= c.label :name %>
  <%= c.text_field :name %>
  <%= c.label :document %>
  <%= c.text_field :document %>
  <%= c.label :email %>
  <%= c.text_field :email %>
  <%= c.submit 'Enviar' %>
<% end %>

app/views/customers/show.html.erb
<dl>
  <dt>Nome:</dt>
  <dd><h1><%= @customer.name %></h1></dd>
  <dt>CPF:</dt>
  <dd><p><%= @customer.document %></p></dd>
  <dt>Email:</dt>
  <dd><p><%= @customer.email %></p></dd>
</dl>
Locações

<table>
  <tr>
    <th><%= Rental.human_attribute_name(:code) %></th>
    <th><%= Rental.human_attribute_name(:start_date) %></th>
    <th><%= Rental.human_attribute_name(:end_date) %></th>
    <th><%= Rental.human_attribute_name(:car_category) %></th>
    <th><%= Rental.human_attribute_name(:status) %></th>
    <th>Ações</th>
  </tr>
  <% @customer.rentals.each do |rental| %>
  <tr>
    <td><%= rental.code %></td>
    <td><%= l rental.start_date %></td>
    <td><%= l rental.end_date %></td>
    <td><%= rental.car_category.name %></td>
    <td><%= Rental.human_attribute_name("status.#{rental.status}") %></td>
    <td>
      <% if rental.scheduled? %>
        <%= link_to 'Iniciar', new_rental_car_rental_path(rental) %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to 'Voltar', customers_path %>