config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index' #> RAIZ ou seja ROOT
  # get '/', to: 'home#index'
  #resources :manufacturers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :manufacturers
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_categories, only: [:index, :show, :new, :create, :edit, :update]
  resources :customers, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
  resources :cars, only: [:index, :show, :new, :create]

  #get 'api/v1/cars', to: 'api#cars'

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index]
    end
  end
end

app/models/car_category.rb
class CarCategory < ApplicationRecord
  has_many :car_models
  has_many :cars, through: :car_models 

  validates :name, uniqueness: true

  validates :name, :daily_rate, :car_insurance, :third_part_insurance, presence: true

  validates :daily_rate, :car_insurance, :third_part_insurance, numericality: { greater_than: 0}
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
  def index
    @carcategories = CarCategory.all
  end

  def show
    @carcategories = CarCategory.find(params[:id])
    #@car_models = CarModel.where(car_category: @carcategories)
  end

  def new
    @carcategory = CarCategory.new
  end

  def create 
    @carcategory = CarCategory.new(carcategory_params)
    if @carcategory.save
      redirect_to @carcategory
    else 
      render :new
    end
  end

  def edit
    @carcategory = CarCategory.find(params[:id])
  end

  def update
    @carcategory = CarCategory.find(params[:id])
    if @carcategory.update(carcategory_params)
      redirect_to @carcategory
    else
      render :new
    end
  end
  private

  def carcategory_params
    params.require(:car_category).permit(:name, :daily_rate, :car_insurance, :third_part_insurance)
  end
end

app/views/car_categories/edit.html.erb
<h1>Editar categoria<h1>

<% @carcategory.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_for @carcategory do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :daily_rate %>
  <%= f.text_field :daily_rate %>
  <%= f.label :car_insurance %>
  <%= f.text_field :car_insurance %>
  <%= f.label :third_part_insurance %>
  <%= f.text_field :third_part_insurance %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/car_categories/index.html.erb
<h1>Categorias de carros</h1>
<ul>
  <% if @carcategories.empty? %>
    <h1>Não há categorias cadastradas</h1>
  <% end %>

  <% @carcategories.each do |m| %>
    <%= link_to m.name, car_category_path(id: m.id) %>
  <% end %>

  <%= link_to 'Registrar nova categoria', new_car_category_path %>
  <%= link_to 'Voltar', root_path %>
</ul>

app/views/car_categories/new.html.erb
<h1>Registra nova categoria<h1>

<% @carcategory.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_for @carcategory do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name %>
  <%= f.label :daily_rate %>
  <%= f.text_field :daily_rate %>
  <%= f.label :car_insurance %>
  <%= f.text_field :car_insurance %>
  <%= f.label :third_part_insurance %>
  <%= f.text_field :third_part_insurance %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/car_categories/show.html.erb
<h1>Categoria <%= @carcategories.name %></h1>
<p><%= number_to_currency(@carcategories.daily_rate) %></p>
<p><%= number_to_currency(@carcategories.car_insurance) %></p>
<p><%= number_to_currency(@carcategories.third_part_insurance) %></p>

<h3>Modelos de carros</h3>
<% @carcategories.car_models.each do |car_model| %>
  <%= link_to car_model.name, car_model %>
<% end %>

<%= link_to 'Editar', edit_car_category_path %>
<%= link_to 'Voltar', car_categories_path %>