config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index' #> RAIZ ou seja ROOT
  # get '/', to: 'home#index'
  #resources :manufacturers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :manufacturers
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_categories, only: [:index, :show, :new, :create, :edit, :update]
  resources :customers, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
  resources :cars, only: [:index, :show, :new, :create]

  #get 'api/v1/cars', to: 'api#cars'

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index]
    end
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :customer
  belongs_to :car_category
  has_one :car_rental 
  has_one :car, through: :car_rental

  before_create :generate_code

  enum status: { scheduled: 0, ongoing: 5 }

  private

  def generate_code
    self.code = loop do
      code = SecureRandom.alphanumeric(6).upcase
      break code unless Rental.exists?(code: code)
    end
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authorize_admin!
  def index
    @rentals = Rental.all
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def new
    @rental = Rental.new
    @customer = Customer.all
    @car_category = CarCategory.all
  end

  def create
    @rental = Rental.create(rental_params)

    RentalsMailer.scheduled(@rental).deliver_now
    
    redirect_to @rental
  end

  def search
    @q = params[:q]
    @rental = Rental.find_by(code: @q.upcase)
    #if @rental.blank? || params[:q].blank?
    #  @rentals = Rental.all
    #  flash.now[:alert] = "Nenhum resultado encontrado para: #{@q}"
    #  render :index
    #end
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date, 
                                    :customer_id, :car_category_id)
  end

  def authorize_admin!
    return if current_user.admin?
    redirect_to root_path, notice: 'Ação não autorizada'
  end
end

app/views/rentals/_rental.html.erb
<dl>
  <dt>Código:</dt>
  <dd><%= rental.code %></dd>
  <dt>Cliente:</dt>
  <dd><%= rental.customer.name %></dd>
  <dt>Categoria:</dt>
  <dd><%= rental.car_category.name %></dd>
  <dt>Data de Início:</dt>
  <dd><%= l rental.start_date %></dd>
  <dt>Data de Término:</dt>
  <dd><%= l rental.end_date %></dd>
  <dt>Status:</dt>
  <dd><%= Rental.human_attribute_name("status.#{rental.status}") %></dd>
</dl>

app/views/rentals/index.html.erb
<h1>Locações</h1>

<%= link_to 'Registrar nova locação', new_rental_path %>

<% if @rentals.empty? %>
  Nenhuma locação cadastrada
<% end %>

<%= form_with url: search_rentals_path, method: :get do |f| %>
  <%= f.label :q, 'Código' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar'%>
<% end %>

<% @rentals.each do |ren| %>
  <h3><%= link_to ren.customer.name, rental_path(id: ren.id) %></h3>
  <%= l ren.start_date %>
  <!--<p><%= link_to 'Ver detalhes', ren, id: "details-#{ren.id}" %></p>-->
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/rentals/new.html.erb
<h1>Nova locação</h1>

<%= form_with model: @rental, local: true do |ren| %>
  <%= ren.label :start_date %>
  <%= ren.date_field :start_date %>
  <%= ren.label :end_date %>
  <%= ren.date_field :end_date %>
  <%= ren.label :customer_id, 'Cliente' %>
  <%= ren.collection_select :customer_id, @customer, :id, :name%>
  <%= ren.label :car_category_id, 'Categoria' %>
  <%= ren.collection_select :car_category_id, @car_category, :id, :name%>
  <%= ren.submit 'Enviar' %>
<% end %>

app/views/rentals/search.html.erb
<% if @rental %>
  <dl>
    <dt>Código:</dt>
    <dd><%= @rental.code %></dd>
    <dt>Data de início:</dt>
    <dd><%= l @rental.start_date %></dd>
    <dt>Data de término:</dt>
    <dd><%= l @rental.end_date %></dd>
    <dt>Cliente:</dt>
    <dd><%= @rental.customer.name %></dd>
    <dt>Categoria:</dt>
    <dd><%= @rental.car_category.name %></dd>
  </dl>
  <%= link_to 'Iniciar', new_rental_car_rental_path(@rental) %>
<% else %>
  <p><%= "Nenhum resultado encontrado para: #{@q}" %></p>
<% end %>

app/views/rentals/show.html.erb
<dl>
  <dt>Código:</dt>
  <dd><%= @rental.code %></dd>
  <dt>Cliente:</dt>
  <dd><%= @rental.customer.name %></dd>
  <dt>Categoria:</dt>
  <dd><%= @rental.car_category.name %></dd>
  <dt>Data de Início:</dt>
  <dd><%= l @rental.start_date %></dd>
  <dt>Data de Término:</dt>
  <dd><%= l @rental.end_date %></dd>
</dl>

<% if @rental.car_rental.present? %>
  <p>Data de início da locação: <%= l @rental.car_rental.created_at, format: :long %></p>
  <p>Carro: <%= @rental.car_rental.car.license_plate %></p>
  <p>Cliente: <%= @rental.customer.email %></p>
  <% if @rental.ongoing?%>
    <p>Status: <%= Rental.human_attribute_name("status.#{@rental.status}") %></p>
  <% end %>
  <p>Locação iniciada por: <%= @rental.car_rental.user.email %></p>
<% end %>

<%= link_to 'Voltar', rentals_path %>